parameters:
    swp_multi_tenancy.path_builder.class: SWP\Component\MultiTenancy\PathBuilder\TenantAwarePathBuilder
    swp_multi_tenancy.candidates_configurator.class: SWP\MultiTenancyBundle\Doctrine\PHPCR\CmfCandidatesConfigurator
    swp_multi_tenancy.phpcr.initializer.class: SWP\MultiTenancyBundle\Initializer\PHPCRBasePathsInitializer
    swp_multi_tenancy.phpcr.generic_initializer.class: Doctrine\Bundle\PHPCRBundle\Initializer\GenericInitializer

services:
    swp_multi_tenancy.phpcr.generic_initializer:
        class: %swp_multi_tenancy.phpcr.generic_initializer.class%
        arguments:
            - Default initializer
            - [ "%swp_multi_tenancy.persistence.phpcr.basepath%" ]
        tags:
            - { name: "doctrine_phpcr.initializer", priority: 100 }

    swp_multi_tenancy.phpcr.initializer:
        class: %swp_multi_tenancy.phpcr.initializer.class%
        arguments:
            - %swp_multi_tenancy.persistence.phpcr.base_paths%
            - "@swp_multi_tenancy.tenant_provider"
            - "@swp_multi_tenancy.path_builder"
            - %swp_multi_tenancy.persistence.phpcr.site_document.class%
        tags:
            - { name: "doctrine_phpcr.initializer", priority: 50 }

    swp_multi_tenancy.path_builder:
        class: %swp_multi_tenancy.path_builder.class%
        arguments:
            - "@swp_multi_tenancy.tenant_resolver"
            - "@swp_multi_tenancy.tenant_context"
            - %swp_multi_tenancy.persistence.phpcr.basepath%
        calls:
            - [setRequestStack, ['@request_stack']]

    swp_multi_tenancy.candidates_configurator:
        class: %swp_multi_tenancy.candidates_configurator.class%
        arguments:
            - "@swp_multi_tenancy.path_builder"
            - %swp_multi_tenancy.persistence.phpcr.route_basepaths%

    swp_multi_tenancy.tenant_aware_router:
        class: %swp_multi_tenancy.persistence.phpcr.router.class%
