language: php

php:
  - 7.3
  - nightly

sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

matrix:
  allow_failures:
    - php: nightly
  fast_finish: true

before_install:
  - composer self-update

env:
  - COMPOSER_FLAGS='update --prefer-stable'
  - COMPOSER_FLAGS='install'

before_script:
  - echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - phpenv rehash
  - composer $COMPOSER_FLAGS --prefer-dist --no-interaction

script:
  - bin/phpunit --coverage-text --debug --verbose
  - bin/phpspec run -fpretty --verbose
