SWP\Component\MultiTenancy\Model\Organization:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            groups: [api]
            type: integer
        name:
            expose: true
            groups: [api]
            type: string
        code:
            expose: true
            groups: [api]
            type: string
